### ISSUE TITLE
Matches are fine I guess, but I get this error

### ISSUE THREAD

**Issue by AndreMPCosta** [simon-weber/Google-Music-Playlist-Importer#6]
Loading library from Google Music...
Matching songs...
48
Traceback (most recent call last):
  File "C:/Users/Andr�/Desktop/Google-Music-Playlist-Importer-master/gm_playlist_importer.py", line 137, in <module>
    main()
  File "C:/Users/Andr�/Desktop/Google-Music-Playlist-Importer-master/gm_playlist_importer.py", line 110, in main
    matched_songs = matcher.match(queries)
  File "C:\Users\Andr�\Desktop\Google-Music-Playlist-Importer-master\gmusicapi\gmtools\tools.py", line 402, in match
    matches += res
TypeError: 'NoneType' object is not iterable

Process finished with exit code 1

By the way, queries that resulted from my local playlist:
http://pastebin.com/kDe5YGEG

I don't know if this helps or not, I can't understand why I'm getting this error.
I fixed it by adding:
if res is not None:
before
matches +=res

meanwhile I have:

Output matches to file or terminal? (f/t): t
Starting match of 86 queries 

And in the end I only got 40 songs on the playlist, where there are some with '==' missing.

EDIT:

Only on the 4th time running the script I got all the songs, kinda weird. 

Is there a way to turn matches less sensitive? For Example locally I have "artist - songx (Original Mix)" as 'Artist' - 'Title' and on GM I have "artist - songx" as 'Artist' - 'Title'. They won't match.

You can close this issue, I made a little script to analyze the id3 info of each song and not rely on the filename to acquire 'title' and 'artist' to build the queries.

**Comment by simon-weber** [comment]
> I fixed it by adding if res is not None...
> Only on the 4th time running the script I got all the songs, kinda weird.

Huh, weird. My best guess is that Google's backend was just being flaky at the time.

> Is there a way to turn matches less sensitive?

You'd have to get creative with the [SearchModifier](https://github.com/simon-weber/Unofficial-Google-Music-API/blob/8262aaaf9f998de7e08ab2ae8cc7ed88bdf47b7b/gmusicapi/gmtools/tools.py#L167) (though, to be totally honest, this code is really old and I'm not sure it all makes sense, haha).

> You can close this issue, I made a little script to analyze the id3 info of each song

Glad you got it working! =)
